# Generated by Django 4.0.2 on 2022-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Tilte')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('Unit', models.IntegerField(verbose_name='Unit')),
                ('Prerequisite', models.CharField(max_length=15, verbose_name='prerequisite')),
                ('Simultaneous', models.CharField(max_length=15, verbose_name='Simultaneous')),
            ],
        ),
    ]
